### PR TITLE
add pre-commit flake module

### PR DESCRIPTION
**Pull request by SeungheonOh**
### Summary of changes

```nix
          pre-commit = {
            settings = {
              src = ./.;
              settings = {
                ormolu.defaultExtensions = [
                  "TypeApplications"
                  "PatternSynonyms"
                ];
              };

              hooks = {
                nixpkgs-fmt.enable = true;
                cabal-fmt.enable = true;
                fourmolu.enable = true;
                hlint.enable = true;
              };
            };
          };
```

### Tested on
- [ ] [agora](https://github.com/Liqwid-Labs/agora)
- [x] [liqwid-libs](https://github.com/Liqwid-Labs/liqwid-libs)
- [ ] [oracle-offchain](https://github.com/Liqwid-Labs/oracle-offchain)
- [ ] ...

### CODE REVIEW

**Comment by SeungheonOh** [comment]
I could make each projects(on/offchain) have independent shell hooks. But I don't really see the point here.

**Review by t4ccer — APPROVED** [review]
LGTM

**Comment by t4ccer** [comment]
Or actually, do we want to remove our hand-rolled format checks and use pre-commit for everything? Or do we want to postpone to give everyone time to adapt to hooks?

**Comment by SeungheonOh** [comment]
I think we should do latter.

**Pull request merged**
